### ISSUE TITLE
Feature request: more error types

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-python#112]
It'd be great to have the following exceptions added so we can handle errors better on the application side:

* `CartoAuthError`
* `CartoSQLError` (or something like that) for syntax problems in query, 'relation does not exist', and others
* `CartoQuotaError` if over quota on LDS, DO, etc. which for now happen on SQL API but maybe this will change in the future?
* `CartoDependentVisError` if someone tries to delete a dataset that has dependent visualizations
* I'm sure there are others

To be able to handle these, we have to inspect the string, which is not a stable way to handle exceptions.

cc @alrocar

**Comment by alrocar** [comment]
Related [comment](https://github.com/CartoDB/cartoframes/pull/621#discussion_r276851968)

**Comment by andy-esch** [comment]
Mostly related to this is https://github.com/CartoDB/carto-python/issues/85, which asks for more information within individual exceptions. E.g., besides an exception, it might be really useful to give http error codes and other information so more granular exceptions can be dealt with

**Comment by Jesus89** [comment]
Dup #1029
