### ISSUE TITLE
warning in BatchSQLClient.create_and_wait_for_completion seems too severe

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-python#113]
Another type of message (or even no message at all) seems more appropriate.
https://github.com/CartoDB/carto-python/blob/867337a9160f220f87e45b68356665ffe3a6d09f/carto/sql.py#L229

The current behavior results in lots of pink warning messages in cartoframes whenever a users uses `CartoContext.execute`:
<img width="1031" alt="Screen Shot 2019-05-06 at 4 54 41 PM" src="https://user-images.githubusercontent.com/1041056/57254622-bedd9300-701f-11e9-8b2f-e5aaf0954027.png">

cc @alrocar

**Comment by cmongut** [comment]
We can close this one because we have removed those warnings :)
