### ISSUE TITLE
ModuleNotFoundError: No module named 'carto.auth'; 'carto' is not a package

### ISSUE THREAD

**Issue by kareemzok** [CartoDB/carto-python#139]
Hello, 

I followed the instructions and did run for the script but I keep getting the following error 

`ModuleNotFoundError: No module named 'carto.auth'; 'carto' is not a package`

What I m missing?

Please advice.

**Comment by kareemzok** [comment]
Issue fixed.

Renamed the file from carto.py to another name

**Comment by tech-team-rural-mda** [comment]
I don't understand the "fix". We're seeing this same error:
```
    from carto.auth import APIKeyAuthClient
ModuleNotFoundError: No module named 'carto'
```
