### ISSUE TITLE
create_vis param seems to be ignored when using FileImport

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/carto-python#14]

**Comment by ohasselblad** [comment]
it works for strings with lower case 't': `create_vis='true'`
`create_vis=True` (python boolean) does not work

**Comment by danicarrion** [comment]
yeah, this is what I was thinking, somehow it's not creating the json correctly. I'll take a look asap

**Comment by alrocar** [comment]
It should be fixed when @danicarrion releases `pyrestcli@0.6.3`

Anyhow this is quite an old issue and carto-python APIs have changed a bit, but the bug was still there.
