### ISSUE TITLE
COPY TO using POST

### ISSUE THREAD

**Issue by oleurud** [CartoDB/carto-python#141]
Comes from https://github.com/CartoDB/cartoframes/issues/778

We recently added [POST support to COPY TO in SQL API](https://github.com/CartoDB/CartoDB-SQL-API/pull/591). Now, we should add the possibility of using POST in COPY TO request here

**Comment by Jesus89** [comment]
@oleurud this could be closed, right?

**Comment by oleurud** [comment]
Yes, thanks!
