### ISSUE TITLE
Return url of import examples

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-python#38]
It'd be nice to return on the console a link to the dataset

**Comment by oriolbx** [comment]
done, for the sync import I can't get directly the table name. The name parameter returns None.

**Comment by alrocar** [comment]
sync-tables API seems to work a bit different.

I'll take a look into it

**Comment by alrocar** [comment]
Added a new example file `import_sync_table_as_dataset.py`. There is a new `DatasetManager` that does the trick.
