### ISSUE TITLE
request: basemap url is url stem before `/api/...` instead of including `/api/`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-python#45]
As far as I understand, baseurls in the v1.0.0 version of this module need to be structured like this:
```
https://eschbacher.carto.com/api/
```

Other pieces of carto's stack don't include the `/api/` piece, like carto(db).js's support for on-prem, etc.: https://github.com/CartoDB/carto-workshop/blob/master/05-apis/exercises/maps_api_guide.md#custom-api-endpoints

To be consistent with these tools, it'd be nice to have a cleaner way of sending the baseurl to other carto services without having to do string operations.

cc @danicarrion

**Comment by danicarrion** [comment]
Makes sense, thanks for pointing that out

**Comment by alrocar** [comment]
Merged in branch 1.0.0
