### ISSUE TITLE
Either fix to work with both 2 and 3 or clearly specify that it only works with 2.?

### ISSUE THREAD

**Issue by BruceEckel** [CartoDB/carto-python#50]
I just spent a couple of hours discovering that this library only works with Python 2. I only tried it with 2.7 so I don't know which particular versions of 2 it works with.

The library installs without any problem on Python 3.5, and can be imported, but doesn't work.

**Comment by danicarrion** [comment]
We're working on version 1.0.0, which will be compatible with both Python 2 and 3. It'll be released in a few weeks, but it's already usable (branch 1.0.0, but please take into account the docs haven't been updated yet).

Sorry for the inconvenience.

**Comment by alrocar** [comment]
Fixed in branch `1.0.0`

CI is enabled and running tests over Python 2.7, 3.6 and nightly builds
