### ISSUE TITLE
feature request: expose params in `sql_client.send`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-python#58]
There are some useful params in the SQL API, such as `skipfields` which allows for some columns to not be included in the API response (e.g., give me all columns except for `the_geom_webmercator`).

cc @alrocar

**Comment by alrocar** [comment]
Hi,

👍 I think we should add it as optional named parameters to the current `send` API.

I've created a branch `1.1.0` so we can start adding new features like this.

Thanks Andy!

**Comment by andy-esch** [comment]
Please ping me if you'd like me to help code it up or do testing!

**Comment by alrocar** [comment]
Of course, feel free to provide a PR for this, It will be highly welcomed ;)

**Comment by alrocar** [comment]
Available in 1.1.0 branch
