### ISSUE TITLE
Fix requests for invalid certificates

### ISSUE THREAD

**Issue by josemazo** [CartoDB/carto-python#59]
Hi!

We are having some problems with this library in OnPremise CARTO instances with invalid certificates and without the chance of use `http`, only `https`.

For fixing this, the [`APIKeyAuthClient`](https://github.com/CartoDB/carto-python/blob/1.0.1/carto/auth.py#L29) class should have a `verify` (or something like that) attribute that refers to the `verify` parameter in [`requests`](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification). We'll need to propagate this change to [`BasicAuthClient`](https://github.com/danicarrion/pyrestcli/blob/v0.6.3/pyrestcli/auth.py#L12), also for setting the using of the `verify` parameter in the `send` method.

We can do that couple of PRs, but we need to now why you convert every boolean to a string [here](https://github.com/danicarrion/pyrestcli/blob/v0.6.3/pyrestcli/auth.py#L74), because the `verify` parameter needs to be a boolean.

Regards.

**Comment by alrocar** [comment]
Hi!

the boolean to string conversion was because of [this](https://github.com/CartoDB/carto-python/issues/14) issue but yes, I think that's not the right place to do it since it's breaking the boolean support in requests

Let me see how to fix that without breaking anything. You can assume the `boolean conversion` will not exist in case you want to provide the PRs (will be very appreciated BTW ;) )

Thanks!

**Comment by alrocar** [comment]
Currently preparing a PR for this

**Comment by josemazo** [comment]
Awesome, we'll check it and prepare the code for inserting the `verify` parameter in another PR(s).

**Comment by alrocar** [comment]
Thanks but it's not necessary, everything comes in #60

Do you mind reviewing?

**Comment by alrocar** [comment]
BTW I found a workaround, it's not necessary to wait for the next release, just pass a proper session instance to the auth client:

```
import requests
session = requests.Session()
session.verify = False

APIKeyAuthClient(the_url, the_api_key, session=session)
```

Hope it helps!
