### ISSUE TITLE
feature request: DatasetManager.delete

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/carto-python#71]
Deleting datasets is an important task, and this library should support it. The call is a 'DELETE' request to `api/v1/viz`.

Like Builder, a call to `DatasetManager.delete` should error/warn if a dataset is connected to a map. I prefer an Error in the Python case. Adding a `force=False|True` will let users force the operation regardless. As far as I know, there's metadata in the api/v1/viz GET that lists the dependents of a table.

**Comment by danicarrion** [comment]
Deleting tables is already supported: https://github.com/CartoDB/carto-python/blob/master/examples/import_and_merge.py#L135, can you please confirm if it's not working?

Will take a look at the warning feature.

**Comment by andy-esch** [comment]
Ah, great, I didn't see delete in the code before.

**Comment by andy-esch** [comment]
Sorry for the noise!
