### ISSUE TITLE
Visualization Manager fields missing values

### ISSUE THREAD

**Issue by ztephm** [CartoDB/carto-python#72]
### Context

The [VisualizationManager](https://github.com/CartoDB/carto-python/blob/eb538edd522cf230cbed527d78b83d515d1062b6/carto/visualizations.py) lets us access many fields to get information about a CARTO account's maps, but the fields below don't return any information.

Can we update carto-python to return these values?
*If it's easier to split these into separate issues please let me know*

* active_child
* active_layer_id
* attributions
* children
* display_name
* external_source
* kind
* license
* liked
* likes
* locked
* map_id
* name
* next_id
* parent_id
* prev_id
* permission
* privacy
* related_tables
* source
* stats
* synchronization
* tags
* title
* transition_options
* type
* uses_builder_features

### Additional Information

Here's the script I used to test: [carto_account_maps_info_all.zip](https://github.com/CartoDB/carto-python/files/1705140/carto_account_maps_info_all.zip)

Here's the dataset generated by the test showing blank fields: [maps_all_info2_save](https://team.carto.com/u/stephaniemongon/dataset/maps_all_info2_save)

These are all of the available fields:

* active_child 
* active_layer_id 
* attributions 
* children 
* client 
* created_at 
* delete 
* description 
* display_name 
* export 
* external_source 
* fields 
* get_collection_endpoint 
* get_id 
* get_resource_endpoint 
* id 
* kind 
* license 
* liked 
* likes 
* locked 
* map_id 
* name 
* next_id 
* parent_id 
* permission 
* prev_id 
* privacy 
* refresh 
* related_tables 
* save 
* send 
* source 
* stats 
* synchronization 
* tags 
* title 
* transition_options 
* type 
* update_from_dict 
* updated_at 
* url 
* uses_builder_features

**Comment by alrocar** [comment]
Thanks for reporting @ztephm

This is next on the queue, hopefully it will be solved this week :)

**Comment by alrocar** [comment]
@ztephm I've added support for some of the fields. 

Changes are living on [this branch](https://github.com/CartoDB/carto-python/tree/1.1.3) maybe you can help me to do the acceptance.

You can install locally that branch with: 

```
pip install -e git+git://github.com/CartoDB/carto-python.git@1.1.3#egg=carto
```

And then run your script.

Take into account that some of the fields you mentioned (children, delete, get_collection_endpoint, get_id, get_resource_endpoint, etc.) are internal to the carto-python implementation. The ones returned by the `viz` API are [this ones](https://github.com/CartoDB/carto-python/blob/1.1.3/carto/visualizations.py#L40-L74).

Finally, I believe some of the fields are unused and probably will be None or empty.

If you find something wrong please tell me :) Let's see if we can release version 1.1.3 this week.

Thanks

**Comment by ztephm** [comment]
Thanks @alrocar ! I re-ran the original script & can confirm I'm seeing values returned for the "missing" list (including `None`).

**Comment by alrocar** [comment]
Thanks! I will release 1.1.3 tomorrow
