### ISSUE TITLE
Dataset Manager fields missing values

### ISSUE THREAD

**Issue by ztephm** [CartoDB/carto-python#73]
### Context

The [VisualizationManager](https://github.com/CartoDB/carto-python/blob/eb538edd522cf230cbed527d78b83d515d1062b6/carto/visualizations.py) lets us access many fields to get information about a CARTO account's maps, but the fields below don't return values even if values should exist—for example my sync tables return 'None' for the synchronizations field.

Can we update carto-python to return these values?
*If it's easier to split these into separate issues please let me know*

* active_child
* active_layer_id
* attributions
* children
* connector
* description
* display_name
* external_source
* license
* next_id
* prev_id
* source
* synchronization
* title
* transition_options
* user

### Additional Information
Here's the script I used to test: [carto_account_datasets_info_all.zip](https://github.com/CartoDB/carto-python/files/1717924/carto_account_datasets_info_all.zip)

These are all of the available fields:
* active_child 
* active_layer_id 
* attributions 
* auth_tokens 
* children 
* client 
* connector 
* created_at 
* delete 
* description 
* display_name 
* external_source 
* fields 
* get_collection_endpoint 
* get_id 
* get_resource_endpoint 
* id 
* kind 
* license 
* liked 
* likes 
* locked 
* map_id 
* name 
* next_id 
* permission 
* prev_id 
* privacy 
* refresh 
* save 
* send 
* source 
* stats 
* synchronization 
* table 
* tags 
* title 
* transition_options 
* type 
* update_from_dict 
* updated_at 
* url 
* user 
* uses_builder_features

**Comment by alrocar** [comment]
Solved through https://github.com/CartoDB/carto-python/pull/74
