### ISSUE TITLE
Synchronization table metadata is wrong

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/carto-python#96]
Synchronization table metadata is wrong. Running something like this:

```python
dm = DatasetManager(auth_client)
dsets = dm.all()

tables = [{
    'name': table.name, 
    'privacy' : table.privacy,
    'created': table.created_at, 
    'synchronization': table.synchronization,
    'geometry': table.table.geometry_types
} for table in dsets]

tables_df = json_normalize(tables)
tables_df.head()
```
All tables presents `None` values:

![image](https://user-images.githubusercontent.com/5215798/48477678-809ab000-e802-11e8-8cfa-a7bd676daf25.png)

But as you can see in my dashboard, there are sync tables:

![image](https://user-images.githubusercontent.com/5215798/48477699-8c867200-e802-11e8-91c9-410260c28620.png)

**Comment by ethervoid** [comment]
Carto-python doesn't include the sync data in the response. I've created a new PR to include it and ask the main contributors about the reason why is not included (just in case)

**Comment by ethervoid** [comment]
There is a new version with that included. Update and voila!
